export const columns = [
  { title: "Name", dataIndex: "name" },
  { title: "Age", dataIndex: "age" },
  { title: "Address", dataIndex: "address" },
  { title: "Salary", dataIndex: "salary" },
];

export const data = [
  {
    key: "1",
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
    salary: 35000,
  },
  {
    key: "2",
    name: "Jim Green",
    age: 42,
    address: "Pune, Maharastra",
    salary: 145000,
  },
  {
    key: "3",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    salary: 49000,
  },
  {
    key: "4",
    name: "Ramesh",
    age: 52,
    address: "Vasai, Mumbai",
    salary: 15000,
  },
  {
    key: "5",
    name: "Jack Simpson",
    age: 32,
    address: "New York No. 1 Lake Park",
    salary: 45000,
  },
  {
    key: "6",
    name: "Jimmy",
    age: 42,
    address: "London No. 1 Lake Park",
    salary: 45000,
  },
  {
    key: "7",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    salary: 45000,
  },
  {
    key: "8",
    name: "Dinesh Khaladkar",
    age: 28,
    address: "Sidney No. 1 Lake Park",
    salary: 45000,
  },
  {
    key: "9",
    name: "Rocky",
    age: 42,
    address: "London No. 5 Snake Park",
    salary: 75000,
  },
  {
    key: "10",
    name: "Tim Black",
    age: 32,
    address: "Sidney No. 3",
    salary: 95000,
  },
  {
    key: "11",
    name: "Deepak Khaladkar",
    age: 22,
    address: "Delhi, India",
    salary: 215000,
  },
  {
    key: "12",
    name: "Dhiren",
    age: 35,
    address: "New York No.3 Lake Park",
    salary: 35000,
  },
  {
    key: "13",
    name: "Dheeraj Bhosale",
    age: 28,
    address: "Pune, Maharastra",
    salary: 200000,
  },
  {
    key: "14",
    name: "Mahesh",
    age: 44,
    address: "Dubai, UAE",
    salary: 69000,
  },
];
